[package]
name = "neat"
version = "0.1.0"
authors = ["jspspike <jspspike@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
indexmap = "1.3.2"
rayon = "1.3.0"
serde = "1.0.115"

[dev-dependencies]
snake = { path = "../snake" }

[profile.release]
lto = true
